### ISSUE TITLE
Entity is currently unavailable

### ISSUE THREAD

**Issue by GLD-NL** [mletenay/home-assistant-goodwe-inverter#85] opened 2021-10-29 16:58 UTC
Hi everyone,

This is realy a nice integration for the GoodWe inverters! But i have a question and can't find the answer. When it is dark and the inverter is offline. I get the status "Entity is currently unavailable" This is thrue ofcourse. But is is possible give a other status than this? This gives a ugly interface.

Is it possible to do something with the status information when the inverter is offline?

Is there someone with a great idea to solve this cosmetic issue?

![image](https://user-images.githubusercontent.com/59057724/139473435-fb6f9b86-b917-4503-9fa0-f58af0e4744f.png)
![image](https://user-images.githubusercontent.com/59057724/139473586-63fbcbbc-223c-441e-8572-3e3f61a4af82.png)

**Comment by lyricnz** [comment] 2022-12-02 01:39
This is fairly much a duplicate of #93 

If you want to wrap the honest "unavailable" with another value (like zero), you can wrap it in a template sensor as described at https://github.com/mletenay/home-assistant-goodwe-inverter/issues/93#issuecomment-1005488515

**Closed** 2023-02-22 20:36 UTC
