### ISSUE TITLE
POWER_VOLT_AMPERE_REACTIVE  and STATE_UNLOCKED 

### ISSUE THREAD

**Issue by alexcool83** [mletenay/home-assistant-goodwe-inverter#317] opened 2024-10-13 05:58 UTC
Registratore: homeassistant.const
Fonte: helpers/deprecation.py:197
Prima occorrenza: 07:39:47 (2 occorrenze)
Ultima registrazione: 07:39:58

POWER_VOLT_AMPERE_REACTIVE was used from goodwe, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'goodwe' custom integration
STATE_UNLOCKED was used from nodered, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.UNLOCKED instead, please report it to the author of the 'nodered' custom integration

**Comment by dirkbe** [comment] 2024-11-03 16:50
First issue is a duplicate of #309, fix is already merged to master.

2nd log message should be related to nodered and reported/fixed there.

**Closed** 2024-12-27 14:38 UTC
